name: market_place_v1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  # Para manejo de llamadas HTTP (REST API)
  dio: ^5.4.3+1

  # Manejo de JSON
  json_annotation: ^4.9.0

  # Autenticación con tokens JWT
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.3

  # Manejo de estados (Riverpod 2025)
  flutter_riverpod: ^2.5.1

  # Navegación moderna
  go_router: ^14.0.2

  # Tipografías de Google
  google_fonts: ^6.2.1

  # Animaciones Lottie (si las usas en tu UI)
  lottie: ^3.1.0
  formz: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  json_serializable: ^6.8.0
  font_awesome_flutter: ^10.7.0
flutter:
  uses-material-design: true
  assets:
    - .env